sheetId="13ZLkgo6a8NfhRtBZekDd9Lh6I_zLACt7ufop8hrnOp0"
tabHotelSede="hotel-sede"
tabBeneficios="Beneficios"
connectionName="gsheets"
connectionHotel="hotelSede"
connectionOnboarding="onboarding"
connectionformBuddy="formBuddy"
driveFolderId="1kmJnV6Xvjg6dR7vTdQHUV5VDH6sWHuYj"
estados=["Iniciado","Carta Enviada", "Falta Info/Doc", "Firmado", "Cancelado"]
tipoContrato= ["Fijo indefinido", "Temporal de sustitución", "Discontinuo", "Otro"]